#!/bin/bash
# Blocks writes into build/dependency dirs and binary files.
# PreToolUse hook for Edit|Write. Exit 2 = block.

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
[ -z "$FILE_PATH" ] && exit 0

case "$FILE_PATH" in
  node_modules/*|*/node_modules/*) REASON="Cannot write into node_modules/ — use the package manager." ;;
  *.next/*) REASON="Cannot write into .next/ — it's generated by the build." ;;
  dist/*|*/dist/*|build/*|*/build/*) REASON="Cannot write into build output directories." ;;
  *) REASON="" ;;
esac
if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a) REASON="Cannot hand-write binary files." ;;
  *.zip|*.tar|*.tar.gz|*.tgz|*.rar|*.7z) REASON="Cannot write archive files." ;;
  *.mp4|*.mov|*.avi|*.mp3|*.wav) REASON="Cannot write media files — add them manually." ;;
  *) REASON="" ;;
esac
if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0
