export const USER_MODEL = "USER_MODEL";
export const PRODUCT_MODEL = "PRODUCT_MODEL";
export const CART_MODEL = "CART_MODEL";
export const ORDER_MODEL = "ORDER_MODEL";
export const WISHLIST_MODEL = "WISHLIST_MODEL";
export const ADDRESS_MODEL = "ADDRESS_MODEL";
export const NOTIFICATION_MODEL = "NOTIFICATION_MODEL";
